# Generated by Django 2.1.7 on 2019-05-18 12:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('bhk', models.IntegerField(default=3)),
                ('square_feet', models.IntegerField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField(default=0)),
                ('elecno', models.CharField(max_length=50)),
                ('wardno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('flat_acquired', models.DateTimeField(default=django.utils.timezone.now)),
                ('mobile_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resident.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resident.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resident.Country')),
            ],
        ),
        migrations.AddField(
            model_name='resident',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resident.State'),
        ),
        migrations.AddField(
            model_name='flat',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resident.Resident'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resident.State'),
        ),
    ]
