# Generated by Django 2.1.7 on 2019-05-18 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField(default=0)),
                ('flat_acquired', models.DateTimeField(default=django.utils.timezone.now)),
                ('moved_out', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flat',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='children',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='flat_acquired',
        ),
        migrations.AddField(
            model_name='flatrecords',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resident.Resident'),
        ),
    ]
