# Generated by Django 2.1.7 on 2019-05-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0002_auto_20190520_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='username',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
